[package]
name = "fu"
description = "Just an Error"
version = "0.1.1"
authors = ["Jordi Calafat <jcalafat97@gmail.com>"]
edition = "2021"
license = "WTFPL"
repository = "https://github.com/jocades/fu"
